version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pwd
    secrets:
      - db_pwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80

  redis:
    image: redis:5.0.3

  phpredisadmin:
    image: actency/docker-phpredisadmin
    ports:
      - '8082:80'
    environment:
      - REDIS_1_HOST=redis
    links:
      - redis

secrets:
  db_pwd:
    file: ./root_db_password.txt
