FROM php:7.3-apache

RUN a2enmod rewrite

RUN rm /etc/apt/preferences.d/no-debian-php
RUN apt-get update && docker-php-ext-install mysqli pdo pdo_mysql
RUN apt-get install -y libzip-dev
RUN docker-php-ext-install zip
RUN apt-get install -y zip unzip php-zip

RUN apt-get update -y && apt-get install -y libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev \
  libfreetype6-dev
RUN apt-get update && \
  apt-get install -y \
  zlib1g-dev
RUN docker-php-ext-install gd

WORKDIR /var/www/html
